### ISSUE TITLE
assumes origin

### ISSUE THREAD

**Issue by jeacott1** [arielf/clean-push#37]
hi,
 nice script, but it seems to assume remotes are at 'origin'. in my case I'm commonly using 'upstream' for example. it would be great if I could pass that alternative in somewhere.
 A few actual usage examples in the readme would also be v helpful instead of needing to read the script to see what the options are.

Cheers.

**Comment by arielf** [comment]
Fixed to use `$UPSTREAM` from env (iff set) and only if not, default to 'origin'.
Not sure if this is the ideal/desired fix. If not please comment.

Still need to improve documentation, so leaving this open.

**Comment by arielf** [comment]
Documentation updated in last merge today.
