### ISSUE TITLE
a few quick examples

### ISSUE THREAD

**Issue by reharik** [arielf/clean-push#45]
Hi, this looks promising.  It would be nice to have a few quick examples of how to use it.  I presume I clone this repo and maybe copy the two files clean-push and 4-way-diff into my repo?  Then call them via `sh clean-push` on the command line.  I can, and will figure it out, but it would be nice if you just spoon fed it to me :)
Thanks.

**Comment by arielf** [comment]
Hi Raif,

There's no need to call the two utilities with a 'sh' prefix.
Assuming they are executables they can be run directly by just naming them.
They just need to be copied to some directory, which is in your PATH.
`This assumes some Unix like env (Linux, FreeBSD, Mac OS-X)
Added what's missing to the README.md (under a HOWTO section).
Hopefully this is enough to get you going.
If not, please let me know how can I make this better for everyone.

One thing you should know is that it is possible that this requires a modern version of bash.
If you have really old bash (3.x), you may need to get bash 4.x or 5.x.

Run:

     bash --version

to find your version.
